name: CI


permissions:
  contents: read
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  DENO_DIR: deno_dependency_cache


jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          # note that deno 2.2.2 currently has a node:sqlite bug that breaks our tests https://github.com/denoland/deno/issues/28309
          deno-version: canary


      - name: Cache Deno dependencies 
        uses: actions/cache@v3
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}

      - name: Lint
        run: deno lint --ignore=deno_dependency_cache

      - name: Test
        run: deno task test

      - name: Lint Documentation Examples
        run: deno test --doc src/**/*.ts

      - name: Lint JSR Publish
        run: deno publish --dry-run

  publish:
    runs-on: ubuntu-latest
    needs: test

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Cache Deno dependencies 
        uses: actions/cache@v3
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}

      - name: Publish to JSR
        if: github.ref == 'refs/heads/main'
        run: deno publish --allow-slow-types
