name: CI


permissions:
  contents: read
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  DENO_DIR: deno_dependency_cache


jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12] #, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x


      - name: Cache Deno dependencies 
        uses: actions/cache@v2
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}

      # - name: Lint
      # lint source code & jsr publish requirements. Currently disabled because we should get jsr published before addressing
      #   run: deno lint --ignore=deno_dependency_cache

      - name: Test
        run: deno task test

      # - name: Lint Publish JSR
      #   run: deno publish --dry-run

  publish:
    runs-on: ubuntu-latest
    needs: test

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Setup repo
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Publish package
        if: github.ref == 'refs/heads/main'
        run: deno publish --allow-slow-types
